/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminFrame.java
 *
 * Created on 20 nov. 2011, 21:58:58
 */
package View;

import Model.ClientRepository;
import Model.DataModel;
import Model.Facture;
import Model.FactureRepository;
import Model.ProduitRepository;
import java.awt.Point;
import javax.swing.JFileChooser;

/**
 *
 * @author kmeleon
 */
public class AdminFrame extends javax.swing.JFrame {

    /** Creates new form AdminFrame */
    public AdminFrame() {
        this.dataModel = new DataModel();
        this.clientRep = new ClientRepository(this.dataModel);
        this.produitRep = new ProduitRepository(this.dataModel);
        this.factureRep = new FactureRepository(this.dataModel);
        this.produitRep.loadData();
        this.factureRep.loadData();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        produits = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableProduit = new javax.swing.JTable();
        utilisateur = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableUser = new javax.swing.JTable();
        factures = new javax.swing.JPanel();
        tabbedContenue = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableContenu = new javax.swing.JTable();
        tabbedFacture = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFacture = new javax.swing.JTable();
        buttonEnregistrer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelSousTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelRemise = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenu();
        menuItemAjouterUser = new javax.swing.JMenuItem();
        menuProduit = new javax.swing.JMenu();
        menuItemAjouterProduit = new javax.swing.JMenuItem();

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("View/Bundle"); // NOI18N
        setTitle(bundle.getString("AdminFrame.title")); // NOI18N
        setLocation(new Point(640-(this.getWidth()/2),0));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 908, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 208, Short.MAX_VALUE)
        );

        tableProduit.setModel(this.produitRep);
        tableProduit.setDefaultRenderer(Object.class, new JTableRender());
        tableProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableProduit);

        org.jdesktop.layout.GroupLayout produitsLayout = new org.jdesktop.layout.GroupLayout(produits);
        produits.setLayout(produitsLayout);
        produitsLayout.setHorizontalGroup(
            produitsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, produitsLayout.createSequentialGroup()
                .addContainerGap()
                .add(produitsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        produitsLayout.setVerticalGroup(
            produitsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, produitsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("AdminFrame.produits.TabConstraints.tabTitle"), produits); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 908, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 238, Short.MAX_VALUE)
        );

        JtableUser.setModel(this.clientRep);
        jScrollPane1.setViewportView(JtableUser);

        org.jdesktop.layout.GroupLayout utilisateurLayout = new org.jdesktop.layout.GroupLayout(utilisateur);
        utilisateur.setLayout(utilisateurLayout);
        utilisateurLayout.setHorizontalGroup(
            utilisateurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .add(utilisateurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        utilisateurLayout.setVerticalGroup(
            utilisateurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 326, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 34, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("AdminFrame.utilisateur.TabConstraints.tabTitle"), utilisateur); // NOI18N

        tableContenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane4.setViewportView(tableContenu);

        tabbedContenue.addTab(bundle.getString("AdminFrame.jScrollPane4.TabConstraints.tabTitle"), jScrollPane4); // NOI18N

        tabbedFacture.setBackground(java.awt.Color.green);

        tableFacture.setModel(this.factureRep);
        tableFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFactureMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableFacture);

        tabbedFacture.addTab(bundle.getString("AdminFrame.jScrollPane3.TabConstraints.tabTitle"), jScrollPane3); // NOI18N

        buttonEnregistrer.setText(bundle.getString("AdminFrame.buttonEnregistrer.text")); // NOI18N
        buttonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnregistrerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13));
        jLabel1.setText(bundle.getString("AdminFrame.jLabel1.text")); // NOI18N

        labelSousTotal.setBackground(java.awt.Color.red);
        labelSousTotal.setFont(new java.awt.Font("OCR A Std", 1, 13));
        labelSousTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSousTotal.setText(bundle.getString("AdminFrame.labelSousTotal.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13));
        jLabel3.setText(bundle.getString("AdminFrame.jLabel3.text")); // NOI18N

        labelRemise.setFont(new java.awt.Font("OCR A Std", 1, 13));
        labelRemise.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRemise.setText(bundle.getString("AdminFrame.labelRemise.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText(bundle.getString("AdminFrame.jLabel5.text")); // NOI18N

        labelTotal.setBackground(java.awt.Color.red);
        labelTotal.setFont(new java.awt.Font("OCR A Std", 1, 13));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText(bundle.getString("AdminFrame.labelTotal.text")); // NOI18N

        org.jdesktop.layout.GroupLayout facturesLayout = new org.jdesktop.layout.GroupLayout(factures);
        factures.setLayout(facturesLayout);
        facturesLayout.setHorizontalGroup(
            facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(facturesLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabbedFacture, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 562, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(facturesLayout.createSequentialGroup()
                        .add(111, 111, 111)
                        .add(facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, facturesLayout.createSequentialGroup()
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelRemise, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .add(facturesLayout.createSequentialGroup()
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelSousTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, facturesLayout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labelTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                        .add(14, 14, 14))
                    .add(buttonEnregistrer)
                    .add(tabbedContenue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );
        facturesLayout.setVerticalGroup(
            facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, facturesLayout.createSequentialGroup()
                .add(facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(facturesLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(tabbedFacture, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                    .add(facturesLayout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .add(tabbedContenue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 378, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelSousTotal)
                            .add(jLabel1))
                        .add(18, 18, 18)
                        .add(facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelRemise)
                            .add(jLabel3))
                        .add(18, 18, 18)
                        .add(facturesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelTotal)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                        .add(buttonEnregistrer)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("AdminFrame.factures.TabConstraints.tabTitle"), factures); // NOI18N

        jMenu1.setText(bundle.getString("AdminFrame.jMenu1.text")); // NOI18N

        menuItemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        menuItemQuit.setText(bundle.getString("AdminFrame.menuItemQuit.text")); // NOI18N
        menuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("AdminFrame.jMenu2.text")); // NOI18N
        jMenuBar1.add(jMenu2);

        menuUser.setText(bundle.getString("AdminFrame.menuUser.text")); // NOI18N

        menuItemAjouterUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_MASK));
        menuItemAjouterUser.setText(bundle.getString("AdminFrame.menuItemAjouterUser.text")); // NOI18N
        menuItemAjouterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjouterUserActionPerformed(evt);
            }
        });
        menuUser.add(menuItemAjouterUser);

        jMenuBar1.add(menuUser);

        menuProduit.setText(bundle.getString("AdminFrame.menuProduit.text")); // NOI18N

        menuItemAjouterProduit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.META_MASK));
        menuItemAjouterProduit.setText(bundle.getString("AdminFrame.menuItemAjouterProduit.text")); // NOI18N
        menuItemAjouterProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjouterProduitActionPerformed(evt);
            }
        });
        menuProduit.add(menuItemAjouterProduit);

        jMenuBar1.add(menuProduit);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAjouterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjouterUserActionPerformed
        AddClientFrame addClientFrame = new AddClientFrame();
    }//GEN-LAST:event_menuItemAjouterUserActionPerformed

    private void menuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitActionPerformed
        
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_menuItemQuitActionPerformed
/**
     * 
     * @param evt 
     */
    private void menuItemAjouterProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjouterProduitActionPerformed
       this.ajouterProduit();
    }//GEN-LAST:event_menuItemAjouterProduitActionPerformed
    /**
     * 
     * @param evt 
     */
    private void buttonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnregistrerActionPerformed
        int returnVal = this.fileChooser.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String path = this.fileChooser.getSelectedFile().getPath()+"/";
            
            int row = this.tableFacture.getSelectedRow();
            String ref = (String)this.tableFacture.getModel().getValueAt(row, 0);
            Facture fact = this.factureRep.getFactureByReference(ref);
            fact.generatePdf(path);
            
            
            System.out.println(path);
        } else {
           
        }
    }//GEN-LAST:event_buttonEnregistrerActionPerformed

    private void tableFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFactureMouseClicked
        
        
        int row = this.tableFacture.getSelectedRow();
        String ref = (String)this.tableFacture.getModel().getValueAt(row, 0);
        Facture fact = this.factureRep.getFactureByReference(ref);
        System.out.println(ref);
        this.tableContenu.clearSelection();
        this.tableContenu.setModel(fact.getListProduit());
        this.tableContenu.repaint();
        
        this.labelSousTotal.setText(fact.getListProduit().getPrixTotal()+ " €");
        float prix = fact.getListProduit().getPrixTotal();
        prix = prix - ((prix*fact.getRemise())/100);
        this.labelTotal.setText(prix + " €");
        this.labelRemise.setText("-" +fact.getRemise()+ " %");
        
    }//GEN-LAST:event_tableFactureMouseClicked

    private void tableProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitMouseClicked
        System.out.println(this.tableProduit.getSelectedRow());
    }//GEN-LAST:event_tableProduitMouseClicked
/**
     * 
     */
    private void ajouterProduit() {
        //throw new UnsupportedOperationException("Not yet implemented");
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminFrame().setVisible(true);
                new CaisseFrame();
                
            }
        });
    }
    private DataModel dataModel;
    private ClientRepository clientRep;
    private ProduitRepository produitRep;
    private FactureRepository factureRep;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableUser;
    private javax.swing.JButton buttonEnregistrer;
    private javax.swing.JPanel factures;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelRemise;
    private javax.swing.JLabel labelSousTotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JMenuItem menuItemAjouterProduit;
    private javax.swing.JMenuItem menuItemAjouterUser;
    private javax.swing.JMenuItem menuItemQuit;
    private javax.swing.JMenu menuProduit;
    private javax.swing.JMenu menuUser;
    private javax.swing.JPanel produits;
    private javax.swing.JTabbedPane tabbedContenue;
    private javax.swing.JTabbedPane tabbedFacture;
    private javax.swing.JTable tableContenu;
    private javax.swing.JTable tableFacture;
    private javax.swing.JTable tableProduit;
    private javax.swing.JPanel utilisateur;
    // End of variables declaration//GEN-END:variables

    
}
